<a href="https://colab.research.google.com/github/oluwadamilola/100-days-of-python/blob/main/series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = ['2023-01-20', '2023-04-27', '2023-06-15']
my_series = pd.Series(data)
my_series

0    2023-01-20
1    2023-04-27
2    2023-06-15
dtype: object

In [ ]:
my_series = pd.to_datetime(my_series)
my_series

0   2023-01-20
1   2023-04-27
2   2023-06-15
dtype: datetime64[ns]